---

references: 
    hg38: /net/eichler/vol2/eee_shared/assemblies/hg38/ucsc.hg38.no_alts.fasta

manifest: manifest.filtered.txt
platform: ILLUMINA
params_bwa_mem: ""
input_type: fastq # Options are bam or fastq
rsync_bw_limit: 40000
